---
title: "compile_congress.Rmd"
output: html_document
---

Use this file to parse congress-legislators from the 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
```

Load the `legislators-current.csv` file from the [congress-legislators](https://github.com/unitedstates/congress-legislators) project.

```{r}
legislators_current <- read.csv('data/legislators-current.csv')
legislators_current %>% colnames()
legislators_current %>% head()
```

Select the proper columns.
```{r}
congress <- legislators_current %>% 
  mutate(birthdate=ymd(birthday)) %>% 
  select(bioguide_id, full_name, type, party, state, birthdate, gender) %>% 
  mutate(type=as.factor(type), party=as.factor(party), gender=as.factor(gender)) %>% 
  mutate(birthyear=year(birthdate))

congress_contact <- legislators_current %>% 
  select(bioguide_id, phone, twitter, facebook, youtube, youtube_id, wikipedia_id)

congress_sm %>% head()
congress %>% head()
```

Now save the data.

```{r}
save(congress, congress_contact, file='../../datasets/congress.RData')
```

